FROM registry.access.redhat.com/ubi9/python-39
ADD combine-service.py .
ADD addresses.txt .
RUN pip3.9 install Flask
RUN pip3.9 install Flask-Cors
RUN pip3.9 install requests
EXPOSE 5000
CMD [“python3.9”, “combine-service.py”]
